# Generated by Django 3.2.13 on 2023-05-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeboard',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reviewboard',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
